# Generated by Django 4.0.5 on 2022-06-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_user_object_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_object',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
