# Generated by Django 4.0.5 on 2022-06-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_user_object_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_object',
            name='profile_pic',
            field=models.ImageField(blank=True, default='x152415000kjd52054vdgvd5dscg5026215.png', null=True, upload_to=''),
        ),
    ]
