# Generated by Django 4.0.5 on 2022-06-24 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_profileotof'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileOTOF',
        ),
    ]
