# Generated by Django 4.0.5 on 2022-06-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_new_post_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_post',
            name='posted_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
